### ISSUE TITLE
ProtoReflectionService "server" is null exception

### ISSUE THREAD

**Issue by freynder** [eclipse-vertx/vertx-grpc#22]
### Version

4.3.5

### Context

Encountering exception when querying grpc reflection service

Testing with grpcurl:
`grpcurl -plaintext localhost:8080list`

Exception:
`
15:01:35.948 [vert.x-eventloop-thread-2] ERROR io.vertx.core.impl.ContextBase - Unhandled exception
java.lang.NullPointerException: Cannot invoke "io.grpc.Server.getImmutableServices()" because "server" is null
	at io.grpc.protobuf.services.ProtoReflectionService.getRefreshedIndex(ProtoReflectionService.java:93)
	at io.grpc.protobuf.services.ProtoReflectionService.serverReflectionInfo(ProtoReflectionService.java:134)
	at io.grpc.reflection.v1alpha.ServerReflectionGrpc$MethodHandlers.invoke(ServerReflectionGrpc.java:208)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler.startCall(ServerCalls.java:235)
	at io.vertx.grpc.server.impl.GrpcServiceBridgeImpl.lambda$bind$2(GrpcServiceBridgeImpl.java:62)
	at io.vertx.grpc.server.impl.GrpcServerImpl$MethodCallHandler.handle(GrpcServerImpl.java:95)
	at io.vertx.grpc.server.impl.GrpcServerImpl.handle(GrpcServerImpl.java:62)
`

```kotlin
val grpcServer: GrpcServer = GrpcServer.server(vertx)
val mainBridge = GrpcServiceBridge.bridge(MainBridge())
val reflectionBridge = GrpcServiceBridge.bridge(ProtoReflectionService.newInstance())
mainBridge.bind(grpcServer)
reflectionBridge.bind(grpcServer)

httpServer = vertx
  .createHttpServer(httpOptions)
  .requestHandler(grpcServer)
  //.requestHandler(router)
  .listen(appConfig.webPort).await()
```

**Comment by tsegismont** [comment]
Thank you for reporting. This is not supported by `vertx-grpc`. As a workaround, you can start `grpcurl` by providing the proto files.

**Comment by yizmailovSF** [comment]
@tsegismont Hey, is there a plan to support ProtoReflectionService in the near future?

**Comment by vietj** [comment]
we should open a feature request for this and open it to contributions
